name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Source/Quartzmin.sln

      - name: Build
        run: dotnet build Source/Quartzmin.sln --configuration Release --no-restore

      - name: Pack
        run: dotnet pack Source/Quartzmin.sln --configuration Release --no-build --output nupkgs

      - name: Add GitHub source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push "nupkgs/*.nupkg" --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
